// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7zr0K4dO2gzfpyMpNKULADL8P-z3YFAY',
    appId: '1:223187958005:web:f82d6340f3d0925a246dbc',
    messagingSenderId: '223187958005',
    projectId: 'e-commerce-50226',
    authDomain: 'e-commerce-50226.firebaseapp.com',
    storageBucket: 'e-commerce-50226.firebasestorage.app',
    measurementId: 'G-YGCM9JLKGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAmD-pVHUtjDSvSuc44MfrfNCQkyqEh5c',
    appId: '1:223187958005:android:9d4e6fa4f809852a246dbc',
    messagingSenderId: '223187958005',
    projectId: 'e-commerce-50226',
    storageBucket: 'e-commerce-50226.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPDyPFzulo5Lb3J2usZmJ0ndk1Frq6ai4',
    appId: '1:223187958005:ios:8389d08387a80c4b246dbc',
    messagingSenderId: '223187958005',
    projectId: 'e-commerce-50226',
    storageBucket: 'e-commerce-50226.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppApi26',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPDyPFzulo5Lb3J2usZmJ0ndk1Frq6ai4',
    appId: '1:223187958005:ios:e1afc0df6ab85f45246dbc',
    messagingSenderId: '223187958005',
    projectId: 'e-commerce-50226',
    storageBucket: 'e-commerce-50226.firebasestorage.app',
    iosBundleId: 'com.ecomese.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7zr0K4dO2gzfpyMpNKULADL8P-z3YFAY',
    appId: '1:223187958005:web:aa4ae1e274a2772e246dbc',
    messagingSenderId: '223187958005',
    projectId: 'e-commerce-50226',
    authDomain: 'e-commerce-50226.firebaseapp.com',
    storageBucket: 'e-commerce-50226.firebasestorage.app',
    measurementId: 'G-6B3EZ5DSG5',
  );
}
